version: "1.1"
name: Step CI Action
uses: stepci/stepci@2.6.3
tests:
    example:
        steps:
            - name: Query
              http:
                  url: http://localhost:4000
                  trpc:
                      query:
                          paymasters/all: {}
                  captures:
                      ok:
                          jsonpath: $.ok
